version: '3.7'

services:
  nginx:
    image: nginx:latest
    volumes:
      - /var/www/shatynska.in.ua/:/var/www
      - /var/www/shatynska.in.ua/_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8082:80
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.shatynska.entrypoints=https"
      - "traefik.http.routers.shatynska.rule=Host(`${DOMEN}`)"
      - "traefik.http.routers.shatynska.tls=true"
      - "traefik.http.routers.shatynska.tls.certresolver=letsEncrypt"
    networks:
      - traefik-public
      - default
    depends_on:
      - app

  app:
    image: getaniftywebsite/php:latest
    volumes:
      - /var/www/shatynska.in.ua/:/var/www
      - /var/www/shatynska.in.ua/_docker/app/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      HOSTNAME_DB: db
      USERNAME_DB: ${USER_NAME}
      PASSWORD_DB: root
      BASENAME: ${DATABASE_NAME}
    depends_on:
      - db
    networks:
      - default

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - /var/www/shatynska.in.ua/tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${USER_NAME}
      MYSQL_PASSWORD: root
    ports:
      - 8182:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    labels:
      - traefik.enable=false
    networks:
      - default

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD_FILE: root
    restart: always
    ports:
      - 8282:80
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.shatynskapma.entrypoints=https"
      - "traefik.http.routers.shatynskapma.rule=Host(`pma.${DOMEN}`)"
      - "traefik.http.routers.shatynskapma.tls=true"
      - "traefik.http.routers.shatynskapma.tls.certresolver=letsEncrypt"
    depends_on:
      - db
    networks:
      - traefik-public
      - default

networks:
  traefik-public:
    external: true
  default:
